### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by emanuelen5** [seanliang/HighlightWords#31]
I am developing a plugin with almost identical feature set [Word-highlighter (name subject to change)](https://github.com/emanuelen5/Word-highlighter) and wanted to publish my package on Package Control and therefore issued a [pull request](https://github.com/wbond/package_control_channel/pull/7417). However, the maintainers quickly noted that my package is eerily similar to yours.

They therefore suggested that I should reach out to you and see if you are still maintaining this package, as well if you accept pull requests. I however do not feel like taking your package and turning it into mine since that would require a lot of work for me (writing test cases all over etc.).

Do you feel like our plugins are too similar to coexist on PC (don't consider the name - it will change before being published on PC)?

**Comment by xacid** [comment]
I am not the owner but was an contributor.
I installed Word-highlighter and played around a bit. Some comments:
1. Good see the color palette is configurable through the file (that has been long-requested here). It will be even better if the file is accessible from the menu.
2. "Edit highlight color" doesn't work for some color schemes.
3. I personally feel the keys are too long. Using the menu to edit it, I got "error: The settings file "res://Packages/word_highlighter/Controls/Default (Windows).sublime-keymap" could not be opened".

**Comment by emanuelen5** [comment]
Hi, thanks for the comments.

1. Sure, I can add the scheme template to the menu.
2. This is hard to investigate without more details.
3. Fixed the error and added test cases for it.

You’re welcome to submit issues to the Github page if you have any more comments or suggestions.

**Comment by seanliang** [comment]
@emanuelen5 Sorry for the late response. I've invite you as a collaborator, please feel free to make your changes.

**Comment by emanuelen5** [comment]
Sure, I can be a collaborator. However, I do not think our plugins are similar enough to be completely merged. Also, adding coverage testing etc. would be too much work for me.
